### ISSUE TITLE
Extreme(ly variable) loadtime of Celluloid::IO

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid-io#112]
It sometimes takes `180.0230` seconds *only* to load `Celluloid::IO` ... sometimes longer.

On DigitalOcean with a 8 core droplet,
( and previously on a 12 core droplet also )
... purely running `require 'celluloid/io'` under `jRuby 1.7.*`
can range anywhere from `0.003` to `300+` seconds in duration.

( For DigitalOcean ... This started in `Ticket #275167`, and is being strace'd as I go )
/cc: @mitayai, @tonyborries, @joonas, @imbriaco, @bkhamitov, @johnedgar, @raiyu

**Comment by johnl** [comment]
Ruby's SecureRandom uses OpenSSL first, if it's available. All OpenSSL versions try to use /dev/urandom by default. If OpenSSL isn't available, Ruby's SecureRandom fails back to using /dev/urandom directly. urandom never blocks.

But this user is using JRuby, not Ruby. The JVM apparently uses /dev/random by default on Linux.

So this can be fixed by either setting "securerandom.source=file:/dev/urandom" in java.security: http://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html

Or by upgrading to JRuby 1.7.11, which has rewritten SecureRandom to seed only once per thread: http://blog.mogotest.com/2014/03/11/faster-securerandom-in-jruby-1.7.11/

I'd probably do both.

**Comment by digitalextremist** [comment]
You are exactly right @johnl. This is a jRuby specific issue. Those two workarounds are great to know. Without doing either or both of those, I was able to remedy the situation using `haveged` several months back, but I will implement those two measures alongside the more unorthodox approach I've been using.

**Comment by johnl** [comment]
As it's not a bug in celluloid, then can you close the ticket? (I'm presuming the ticket owner can close/reject it - I can't).

**Comment by digitalextremist** [comment]
Closing, this is not a bug in Celluloid.
